164829206 implement CRUD functionality for articles app
andela/ah-centauri-backend pull request #14
Opened 2019-04-04 13:43 UTC by ValerieRono

**Description**
Currently, users can sign up and log in to author's haven. This PR allows our users to create, retrieve, update and delete articles

**Type of Change**
-New feature(non-breaking change which adds functionality)
-This change requires a documentation update

**Checklist**
-My code follows the style guidelines of this project
-I have linted my code prior to submission
-I had added tests
-New and existing unit tests pass locally with my changes

**Pivotal tracker**
#164829206

2019-04-04 15:38 UTC, bl4ck4ndbr0wn requested changes
Try using reverse arguments when implementing your end to end testing for a specific article.
```reverse('authors.apps.articles:articles', args=[slug])```

2019-04-04 15:45 UTC, ValerieRono commented
> Try using reverse arguments when implementing your end to end testing for a specific article.
> `reverse('authors.apps.articles:articles', args=[slug])`

done and done, thank you

2019-04-04 16:31 UTC, bl4ck4ndbr0wn approved these changes

2019-04-05 07:00 UTC, ogiste approved these changes
Permissions issue is resolved. And URLs are all according to the format. Looks good, nice work.

2019-04-05 12:30 UTC, merged