164829224 users should be able to view their comment edit history
andela/ah-centauri-backend pull request #35
Opened 2019-04-24 05:53 UTC by vino-jasuba

#### Description
Currently, users have no way of telling whether a comment has been edited. This feature adds a new property to comments to indicate whether they have been edited or not. Also, it enables the comment author to view their edit history.

#### Type of change
- [ ] Bug fix (nonbreaking change which fixes an issue)
- [x] New feature (nonbreaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

#### How Has This Been Tested?
Please describe the tests that you ran to verify your changes
- [x] End to end
- [x] Integration

This feature adds the following API endpoint:

`/api/comments/{comment_id}/history` 

which returns the edit history with the following JSON structure

```json
{
    "comments": [
        {
            "id": 1,
            "body": "His name was my name three.",
            "created_at": "2019-04-23T10:00:49.830913Z",
            "updated_at": "2019-04-23T10:04:51.696038Z"
        },
        {
            "id": 1,
            "body": "brathe",
            "created_at": "2019-04-23T10:00:49.830913Z",
            "updated_at": "2019-04-23T10:00:49.830942Z"
        }
    ],
    "commentsCount": 2
}
```

PS: Only the author of a comment can view edit history. Everyone else only has the property
`has_edits` to show whether the comment has been edited or not.

```json
{
    "comments": [
        {
            "id": 1,
            "article": "the-3-musketeers",
            "author": "vino",
            "body": "His name was my name three.",
            "created_at": "2019-04-23T10:00:49.830913Z",
            "updated_at": "2019-04-23T10:04:51.696038Z",
            "replies": 0,
            "parent": null,
            "has_edits": true
        }
    ],
    "commentsCount": 1
}
```

#### Checklist:
- [x] My code follows the style guide for this project
- [ ] I have linted my code prior to submission
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

#### Pivotal Tracker
[164829224](https://www.pivotaltracker.com/story/show/164829224)

2019-04-24 10:56 UTC, ValerieRono approved these changes
looks good to me Vincent,

2019-04-24 15:11 UTC, bl4ck4ndbr0wn approved these changes
Great implementation.
LGTM

2019-04-24 15:12 UTC, bl4ck4ndbr0wn requested changes
Kindly resolve all merge conflicts and resolve the coverage percentage by adding more test to your feature.

2019-04-25 08:39 UTC, bl4ck4ndbr0wn approved these changes

2019-04-25 15:53 UTC, merged